### ISSUE TITLE
Any chance to revive this project?

### ISSUE THREAD

**Issue by sergiuprt** [sjlu/Virtual-Biology-Lab#2]
Rewriting parts or maybe entirely.

**Comment by Bokonon366** [comment]
I would strongly advise a complete rewrite if you were to try and re-implement this. We built this as a class project a decade ago in college so it was somewhat hacked together over a couple week with Laravel and Flash.

**Comment by sjlu** [comment]
Yeah, no chance that this is going to be revived. Feel free to fork.
